=== DiopAmary/xml-to-json-tp/mondial2.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT mondial (country+)>
<!ELEMENT country (pays, capital, population, superficie, religion*, ville+, frontière*)>
<!ELEMENT pays (#PCDATA)>
<!ELEMENT capital (#PCDATA)>
<!ELEMENT population (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT religion (#PCDATA)>
<!ATTLIST religion
          pourcentage CDATA #REQUIRED>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT frontière (#PCDATA)>

=== DiopAmary/xml-to-json-tp/mondial2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mondial SYSTEM "mondial2.dtd">
<mondial>
            <country><pays>Albania</pays><capital>cty-Albania-Tirane</capital><population>2821977</population><superficie>28750</superficie><religion pourcentage="58.8">Muslim</religion><religion pourcentage="10">Catholic</religion><religion pourcentage="6.8">Christian Orthodox</religion><religion pourcentage="0.1">Protestant</religion><ville>Tirana Tirane</ville><ville>Shkodër</ville><ville>Durrës</ville><ville>Vlorë</ville><ville>Elbasan</ville><ville>Korçë</ville><frontière>GR</frontière><frontière>MK</frontière><frontière>MNE</frontière><frontière>KOS</frontière></country>
            <country><pays>Greece</pays><capital>cty-Greece-Athens</capital><population>10816286</population><superficie>131940</superficie><religion pourcentage="91">Christian Orthodox</religion><religion pourcentage="2">Catholic</religion><religion pourcentage="0.3">Protestant</religion><religion pourcentage="2">Muslim</religion><ville>Komotini</ville><ville>Kavala</ville><ville>Athina Athens</ville><ville>Peiraias Piräus Piraeus</ville><ville>Peristeri</ville><ville>Acharnes</ville><ville>Patra Patras</ville><ville>Kozani</ville><ville>Kerkyra Korfu Corfu</ville><ville>Ioannina</ville><ville>Thessaloniki</ville><ville>Iraklio Iraklion Irakleio</ville><ville>Chania</ville><ville>Ermoupoli</ville><ville>Rhodes Rhodos</ville><ville>Tripoli</ville><ville>Lamia</ville><ville>Chalkida Chalkis Chalcis</ville><ville>Larissa</ville><ville>Volos</ville><ville>Mytilini Mytilene</ville><ville>Karyes</ville><frontière>AL</frontière><frontière>MK</frontière><frontière>BG</frontière><frontière>TR</frontière></country>
            <country><pays>Cyprus</pays><capital>cty-Cyprus-Nicosia</capital><population>1133803</population><superficie>9251</superficie><religion pourcentage="69.6">Christian Orthodox</religion><religion pourcentage="25.3">Muslim</religion><religion pourcentage="3">Catholic</religion><religion pourcentage="2">Protestant</religion><ville>Lefkosia Nicosia</ville><ville>Larnaka Larnaca</ville><ville>Lemesos Limassol</ville></country>
            <country><pays>North Macedonia</pays><capital>cty-Macedonia-Skopje</capital><population>2059794</population><superficie>25333</superficie><religion pourcentage="64.8">Christian Orthodox</religion><religion pourcentage="33.3">Muslim</religion><religion pourcentage="0.2">Catholic</religion><ville>Skopje</ville><ville>Kumanovo</ville><frontière>AL</frontière><frontière>GR</frontière><frontière>SRB</frontière><frontière>KOS</frontière><frontière>BG</frontière></country>
            <country><pays>Serbia</pays><capital>city-Belgrade-SRB-SRB</capital><population>7120666</population><superficie>77474</superficie><religion pourcentage="84.5">Christian Orthodox</religion><religion pourcentage="5.4">Catholic</religion><religion pourcentage="3">Muslim</religion><religion pourcentage="1">Protestant</religion><ville>Beograd Belgrade</ville><ville>Novi Sad</ville><ville>Niš</ville><frontière>H</frontière><frontière>RO</frontière><frontière>BG</frontière><frontière>MK</frontière><frontière>HR</frontière><frontière>BIH</frontière><frontière>MNE</frontière><frontière>KOS</frontière></country>
            <country><pays>Montenegro</pays><capital>city-Podgorica-MNE-MNE</capital><population>620029</population><superficie>14026</superficie><religion pourcentage="72.1">Christian Orthodox</religion><religion pourcentage="19.1">Muslim</religion><religion pourcentage="3.4">Catholic</religion><religion pourcentage="0.1">Protestant</religion><ville>Podgorica</ville><frontière>HR</frontière><frontière>SRB</frontière><frontière>BIH</frontière><frontière>AL</frontière><frontière>KOS</frontière></country>
            <country><pays>Kosovo</pays><capital>city-Pristina-KOS-KOS</capital><population>1733872</population><superficie>10887</superficie><religion pourcentage="95.6">Muslim</religion><religion pourcentage="2.2">Catholic</religion><religion pourcentage="1.5">Christian Orthodox</religion><ville>Prishtine Pristina</ville><frontière>MNE</frontière><frontière>SRB</frontière><frontière>MK</frontière><frontière>AL</frontière></country>
            <country><pays>Andorra</pays><capital>cty-Andorra-Andorra-la-Vella</capital><population>78115</population><superficie>450</superficie><religion pourcentage="90.1">Catholic</religion><religion pourcentage="2.1">Protestant</religion><religion pourcentage="3">Muslim</religion><ville>Andorra la Vella</ville><frontière>F</frontière><frontière>E</frontière></country>
            <country><pays>France</pays><capital>cty-France-Paris</capital><population>64300821</population><superficie>547030</superficie><religion pourcentage="57.5">Catholic</religion><religion pourcentage="9">Muslim</religion><religion pourcentage="3">Protestant</religion><religion pourcentage="0.4">Christian Orthodox</religion><religion pourcentage="0.8">Jewish</religion><religion pourcentage="0.6">Buddhist</religion><religion pourcentage="0.3">Hindu</religion><ville>Paris</ville><ville>Boulogne-Billancourt</ville><ville>Argenteuil</ville><ville>Montreuil</ville><ville>Saint-Denis</ville><ville>Clermont-Ferrand</ville><ville>Lyon</ville><ville>Grenoble</ville><ville>Saint-Étienne</ville><ville>Villeurbanne</ville><ville>Bordeaux</ville><ville>Limoges</ville><ville>Lille</ville><ville>Amiens</ville><ville>Calais</ville><ville>Marseille</ville><ville>Nice</ville><ville>Toulon</ville><ville>Aix-en-Provence</ville><ville>Rennes</ville><ville>Brest</ville><ville>Orléans</ville><ville>Tours</ville><ville>Nantes</ville><ville>Angers</ville><ville>Le Mans</ville><ville>Strasbourg</ville><ville>Mulhouse</ville><ville>Metz</ville><ville>Nancy</ville><ville>Reims</ville><ville>Rouen</ville><ville>Le Havre</ville><ville>Caen</ville><ville>Dijon</ville><ville>Besançon</ville><ville>Toulouse</ville><ville>Montpellier</ville><ville>Nîmes</ville><ville>Perpignan</ville><ville>Ajaccio</ville><frontière>AND</frontière><frontière>E</frontière><frontière>D</frontière><frontière>I</frontière><frontière>CH</frontière><frontière>B</frontière><frontière>L</frontière><frontière>MC</frontière></country>
            <country><pays>Spain</pays><capital>cty-Spain-Madrid</capital><population>46815916</population><superficie>504750</superficie><religion pourcentage="68.9">Catholic</religion><religion pourcentage="4.1">Muslim</religion><religion pourcentage="2.6">Protestant</religion><religion pourcentage="2">Christian Orthodox</religion><religion pourcentage="0.25">Jehovas Witnesses</religion><religion pourcentage="0.14">Jewish</religion><religion pourcentage="0.1">Mormon</religion><ville>Sevilla Seville</ville><ville>Almería</ville><ville>Cádiz</ville><ville>Córdoba</ville><ville>Granada</ville><ville>Huelva</ville><ville>Málaga</ville><ville>Jerez de la Frontera Jerez</ville><ville>Jaén</ville><ville>Algeciras</ville><ville>Marbella</ville><ville>Dos Hermanas</ville><ville>Zaragoza</ville><ville>Oviedo</ville><ville>Gijón</ville><ville>Palma de Mallorca Palma</ville><ville>Vitoria-Gasteiz</ville><ville>Bilbao</ville><ville>Barakaldo</ville><ville>Donostia San Sebastián Donostia-San Sebastián</ville><ville>Santa Cruz de Tenerife</ville><ville>San Cristóbal de La Laguna La Laguna</ville><ville>Las Palmas de Gran Canaria Las Palmas</ville><ville>Telde</ville><ville>Santander</ville><ville>Valladolid</ville><ville>Burgos</ville><ville>León</ville><ville>Salamanca</ville><ville>Toledo</ville><ville>Albacete</ville><ville>Barcelona</ville><ville>Lleida</ville><ville>Tarragona</ville><ville>Reus</ville><ville>Hospitalet de Llobregat L'Hospitalet de Llobregat</ville><ville>Badalona</ville><ville>Sabadell</ville><ville>Terrassa</ville><ville>Santa Coloma de Gramenet</ville><ville>Mataró</ville><ville>Badajoz</ville><ville>Merida</ville><ville>A Coruña La Coruna</ville><ville>Vigo</ville><ville>Ourense</ville><ville>Santiago de Compostela</ville><ville>Madrid</ville><ville>Móstoles</ville><ville>Leganés</ville><ville>Alcalá de Henares</ville><ville>Fuenlabrada</ville><ville>Getafe</ville><ville>Alcorcón</ville><ville>Torrejón de Ardoz</ville><ville>Parla</ville><ville>Alcobendas</ville><ville>Murcia</ville><ville>Cartagena</ville><ville>Pamplona Iruña</ville><ville>Logroño</ville><ville>Valencia</ville><ville>Alicante Alacant</ville><ville>Elche Elx</ville><ville>Castellón de la Plana Castelló de la Plana</ville><frontière>AND</frontière><frontière>F</frontière><frontière>GBZ</frontière><frontière>P</frontière></country>
            <country><pays>Czech Republic Czechia</pays><capital>cty-Czech-2</capital><population>10562214</population><superficie>78703</superficie><religion pourcentage="10.3">Catholic</religion><religion pourcentage="0.8">Protestant</religion><religion pourcentage="0.2">Muslim</religion><ville>Praha Prague</ville><ville>České Budějovice</ville><ville>Brno</ville><ville>Karlovy Vary</ville><ville>Jihlava</ville><ville>Hradec Králové</ville><ville>Liberec</ville><ville>Ostrava</ville><ville>Olomouc</ville><ville>Pardubice</ville><ville>Plzeň</ville><ville>Ústí nad Labem</ville><ville>Zlín</ville><frontière>A</frontière><frontière>D</frontière><frontière>SK</frontière><frontière>PL</frontière></country>
            <country><pays>Slovakia</pays><capital>cty-Slovakia-Bratislava</capital><population>5397036</population><superficie>48845</superficie><religion pourcentage="65.8">Catholic</religion><religion pourcentage="8.9">Protestant</religion><religion pourcentage="0.9">Christian Orthodox</religion><ville>Bratislava</ville><ville>Banská Bystrica</ville><ville>Žilina</ville><ville>Košice</ville><ville>Prešov</ville><ville>Nitra</ville><ville>Trenčín</ville><ville>Trnava</ville><frontière>A</frontière><frontière>CZ</frontière><frontière>H</frontière><frontière>PL</frontière><frontière>UA</frontière></country>
